//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/New Controls.InputActions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @NewControls: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @NewControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""New Controls"",
    ""maps"": [
        {
            ""name"": ""MouseInput"",
            ""id"": ""f68fe606-1ed9-40e9-ae55-e893f0fbcfce"",
            ""actions"": [
                {
                    ""name"": ""MouseX"",
                    ""type"": ""PassThrough"",
                    ""id"": ""796cda14-7cd4-4101-9824-ad42be247aa3"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MouseY"",
                    ""type"": ""PassThrough"",
                    ""id"": ""18d673e1-8e29-4bf8-a04b-83630afd3709"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MouseWheelUp"",
                    ""type"": ""PassThrough"",
                    ""id"": ""7bbca392-5026-4f05-b08e-2567f6b68aca"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MouseWheelDown"",
                    ""type"": ""PassThrough"",
                    ""id"": ""0538c905-0a27-44c6-8f02-47d24e6116b2"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""98be4ed2-5234-4828-88e3-260015785b4a"",
                    ""path"": ""<Mouse>/delta/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MouseX"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6f7d1a51-7829-4cd7-a791-522b7b58aaa3"",
                    ""path"": ""<Mouse>/delta/y"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Inputs"",
                    ""action"": ""MouseY"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6d6b2691-f1cf-41b4-aaf3-95d223dc4041"",
                    ""path"": ""<Mouse>/scroll/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Inputs"",
                    ""action"": ""MouseWheelDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9bee68d2-fbf3-41eb-ace8-01d1b8815a56"",
                    ""path"": ""<Mouse>/scroll/y"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Inputs"",
                    ""action"": ""MouseWheelUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Inputs"",
            ""bindingGroup"": ""Inputs"",
            ""devices"": [
                {
                    ""devicePath"": ""<VirtualMouse>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // MouseInput
        m_MouseInput = asset.FindActionMap("MouseInput", throwIfNotFound: true);
        m_MouseInput_MouseX = m_MouseInput.FindAction("MouseX", throwIfNotFound: true);
        m_MouseInput_MouseY = m_MouseInput.FindAction("MouseY", throwIfNotFound: true);
        m_MouseInput_MouseWheelUp = m_MouseInput.FindAction("MouseWheelUp", throwIfNotFound: true);
        m_MouseInput_MouseWheelDown = m_MouseInput.FindAction("MouseWheelDown", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // MouseInput
    private readonly InputActionMap m_MouseInput;
    private List<IMouseInputActions> m_MouseInputActionsCallbackInterfaces = new List<IMouseInputActions>();
    private readonly InputAction m_MouseInput_MouseX;
    private readonly InputAction m_MouseInput_MouseY;
    private readonly InputAction m_MouseInput_MouseWheelUp;
    private readonly InputAction m_MouseInput_MouseWheelDown;
    public struct MouseInputActions
    {
        private @NewControls m_Wrapper;
        public MouseInputActions(@NewControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @MouseX => m_Wrapper.m_MouseInput_MouseX;
        public InputAction @MouseY => m_Wrapper.m_MouseInput_MouseY;
        public InputAction @MouseWheelUp => m_Wrapper.m_MouseInput_MouseWheelUp;
        public InputAction @MouseWheelDown => m_Wrapper.m_MouseInput_MouseWheelDown;
        public InputActionMap Get() { return m_Wrapper.m_MouseInput; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(MouseInputActions set) { return set.Get(); }
        public void AddCallbacks(IMouseInputActions instance)
        {
            if (instance == null || m_Wrapper.m_MouseInputActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_MouseInputActionsCallbackInterfaces.Add(instance);
            @MouseX.started += instance.OnMouseX;
            @MouseX.performed += instance.OnMouseX;
            @MouseX.canceled += instance.OnMouseX;
            @MouseY.started += instance.OnMouseY;
            @MouseY.performed += instance.OnMouseY;
            @MouseY.canceled += instance.OnMouseY;
            @MouseWheelUp.started += instance.OnMouseWheelUp;
            @MouseWheelUp.performed += instance.OnMouseWheelUp;
            @MouseWheelUp.canceled += instance.OnMouseWheelUp;
            @MouseWheelDown.started += instance.OnMouseWheelDown;
            @MouseWheelDown.performed += instance.OnMouseWheelDown;
            @MouseWheelDown.canceled += instance.OnMouseWheelDown;
        }

        private void UnregisterCallbacks(IMouseInputActions instance)
        {
            @MouseX.started -= instance.OnMouseX;
            @MouseX.performed -= instance.OnMouseX;
            @MouseX.canceled -= instance.OnMouseX;
            @MouseY.started -= instance.OnMouseY;
            @MouseY.performed -= instance.OnMouseY;
            @MouseY.canceled -= instance.OnMouseY;
            @MouseWheelUp.started -= instance.OnMouseWheelUp;
            @MouseWheelUp.performed -= instance.OnMouseWheelUp;
            @MouseWheelUp.canceled -= instance.OnMouseWheelUp;
            @MouseWheelDown.started -= instance.OnMouseWheelDown;
            @MouseWheelDown.performed -= instance.OnMouseWheelDown;
            @MouseWheelDown.canceled -= instance.OnMouseWheelDown;
        }

        public void RemoveCallbacks(IMouseInputActions instance)
        {
            if (m_Wrapper.m_MouseInputActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IMouseInputActions instance)
        {
            foreach (var item in m_Wrapper.m_MouseInputActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_MouseInputActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public MouseInputActions @MouseInput => new MouseInputActions(this);
    private int m_InputsSchemeIndex = -1;
    public InputControlScheme InputsScheme
    {
        get
        {
            if (m_InputsSchemeIndex == -1) m_InputsSchemeIndex = asset.FindControlSchemeIndex("Inputs");
            return asset.controlSchemes[m_InputsSchemeIndex];
        }
    }
    public interface IMouseInputActions
    {
        void OnMouseX(InputAction.CallbackContext context);
        void OnMouseY(InputAction.CallbackContext context);
        void OnMouseWheelUp(InputAction.CallbackContext context);
        void OnMouseWheelDown(InputAction.CallbackContext context);
    }
}
